"""
Episode runner for the mother/child attachment simulation.

Takes events from event_generator.py and runs them through the two
fine-tuned adapters, producing transcripts.

Each event is a three-part exchange:

    1. child bid       -- scripted from the event template
    2. mother response -- GENERATED by adapters/mother, with the
                          event's availability context appended to her
                          system prompt
    3. child reaction  -- GENERATED by adapters/child, responding to
                          what the mother actually said

Step 3 is the one that matters. The child's reaction to how a bid was
met is what carries the attachment signal -- it is the thing emotion
vectors get extracted from later, and the thing GRPO eventually scores
mother candidates against.

Both adapters stay loaded simultaneously (~9GB total at 4-bit) rather
than being swapped per turn, which would make a run unusably slow.

Usage:
    python src/core/run_episodes.py events_high_reliability.jsonl
    python src/core/run_episodes.py events_low_reliability.jsonl --episodes 3
    python src/core/run_episodes.py events_low_reliability.jsonl --out run_low.jsonl
"""

import argparse
import json
import time
from collections import defaultdict

from mlx_lm import load, generate
from mlx_lm.sample_utils import make_sampler

BASE_MODEL = "mlx-community/Meta-Llama-3.1-8B-Instruct-4bit"
MOTHER_ADAPTER = "adapters/mother_v4"
CHILD_ADAPTER = "adapters/child_v4"

MOTHER_SYSTEM = (
    "You are playing the role of a mother in a simulated household, "
    "interacting with your child. Respond in character, however you "
    "would naturally respond in the moment -- this is not always "
    "going to be perfectly patient or attentive. "
    "Reply with only the words you say out loud. Do not narrate "
    "actions, do not describe yourself, do not write prose."
)

CHILD_SYSTEM = (
    "You are playing the role of a young child, around 6-8 years old, "
    "in a simulated household, interacting with your mother. Respond "
    "in character as a child would, however you would naturally react "
    "in the moment. "
    "Reply with only the words you say out loud. Do not narrate "
    "actions, do not describe yourself, do not write prose."
)

TEMP = 0.8
MAX_TOKENS = 80

# How many prior exchanges from the same episode to carry forward as
# context. Set to 0: each event is a self-contained situation, and the
# child already receives its own bid via extra_context, so carried
# history only caused agents to blend a previous event into the current
# one (a mother answering "my tooth hurts" with "but first show me that
# thing you made"). Cross-episode learning lives in the WEIGHTS, not in
# the context window, so nothing is lost here.
CONTEXT_TURNS = 0


def build_messages(system, history, user_line, extra_context=None):
    """history is a list of (role, text) pairs, oldest first."""
    system_content = system
    if extra_context:
        # Phrased as a constraint on what you can do, not as a scene to
        # describe. The earlier "Right now: ..." framing read as
        # scene-setting and produced prose narration in the output.
        system_content = f"{system}\n\nYour situation: {extra_context}"

    messages = [{"role": "system", "content": system_content}]
    for role, text in history:
        messages.append({"role": role, "content": text})
    messages.append({"role": "user", "content": user_line})
    return messages


def recent(history, turns):
    """Last `turns` exchanges, or nothing at all when turns == 0.

    Written out rather than inlined because history[-turns * 2:] is a
    trap: at turns == 0 that becomes history[-0:], which is history[0:],
    i.e. the ENTIRE list rather than an empty one. That silently gave
    every agent the full episode history and produced cross-event bleed
    (a mother answering a bid about a scored goal with "first let's get
    you that cold washcloth" from an injury two events earlier).
    """
    if turns <= 0:
        return []
    return history[-turns * 2:]


def say(model, tokenizer, sampler, messages):
    prompt = tokenizer.apply_chat_template(messages, add_generation_prompt=True)
    return generate(
        model,
        tokenizer,
        prompt=prompt,
        max_tokens=MAX_TOKENS,
        sampler=sampler,
        verbose=False,
    ).strip()


def load_events(path, max_episodes=None):
    events = []
    with open(path) as f:
        for line in f:
            ev = json.loads(line)
            if max_episodes is not None and ev["episode"] >= max_episodes:
                continue
            events.append(ev)
    return events


def group_by_episode(events):
    grouped = defaultdict(list)
    for ev in events:
        grouped[ev["episode"]].append(ev)
    for ep in grouped.values():
        ep.sort(key=lambda e: e["index"])
    return dict(sorted(grouped.items()))


def run(events_path, out_path, max_episodes, verbose):
    events = load_events(events_path, max_episodes)
    episodes = group_by_episode(events)

    print(f"loading {MOTHER_ADAPTER} ...")
    mother_model, mother_tok = load(BASE_MODEL, adapter_path=MOTHER_ADAPTER)
    print(f"loading {CHILD_ADAPTER} ...")
    child_model, child_tok = load(BASE_MODEL, adapter_path=CHILD_ADAPTER)
    sampler = make_sampler(temp=TEMP)

    n_events = sum(len(evs) for evs in episodes.values())
    print(f"\nrunning {len(episodes)} episodes, {n_events} events\n")

    records = []
    started = time.time()
    done = 0

    for ep_idx, ep_events in episodes.items():
        # Context resets at the episode boundary by design.
        mother_history = []
        child_history = []

        if verbose:
            print(f"\n{'=' * 66}\nEPISODE {ep_idx}\n{'=' * 66}")

        for ev in ep_events:
            child_bid = ev["child_utterance"]

            # --- mother responds to the bid ---
            mother_msgs = build_messages(
                MOTHER_SYSTEM,
                recent(mother_history, CONTEXT_TURNS),
                child_bid,
                extra_context=ev["availability_context"],
            )
            mother_line = say(mother_model, mother_tok, sampler, mother_msgs)

            # --- child reacts to what the mother said ---
            # The child must be told what IT just said. Without this the
            # child sees only the mother's line with no antecedent, and
            # imports a reaction from some earlier event instead --
            # e.g. answering "let's look at your cartwheel" with "can I
            # get the bandage?" left over from an injury three turns ago.
            child_msgs = build_messages(
                CHILD_SYSTEM,
                recent(child_history, CONTEXT_TURNS),
                mother_line,
                extra_context=(
                    f'You just said to your mother: "{child_bid}" '
                    f"She is now responding."
                ),
            )
            child_reaction = say(child_model, child_tok, sampler, child_msgs)

            # Each agent's history is from its own point of view:
            # for the mother, the child speaks as "user"; for the
            # child, the mother speaks as "user".
            mother_history += [("user", child_bid),
                               ("assistant", mother_line)]
            child_history += [("user", mother_line),
                              ("assistant", child_reaction)]

            record = {
                "episode": ev["episode"],
                "index": ev["index"],
                "event_type": ev["event_type"],
                "is_bid": ev["is_bid"],
                "availability": ev["availability"],
                "availability_context": ev["availability_context"],
                "child_bid": child_bid,
                "mother_response": mother_line,
                "child_reaction": child_reaction,
            }
            records.append(record)
            done += 1

            if verbose:
                print(f"\n[{ev['index']}] {ev['event_type']} "
                      f"(mother: {ev['availability']})")
                print(f"  child  > {child_bid}")
                print(f"  mother > {mother_line}")
                print(f"  child  > {child_reaction}")
            else:
                elapsed = time.time() - started
                rate = done / elapsed if elapsed else 0
                remaining = (n_events - done) / rate if rate else 0
                print(f"\r  {done}/{n_events} events "
                      f"({remaining / 60:.1f} min left)", end="", flush=True)

    with open(out_path, "w") as f:
        for r in records:
            f.write(json.dumps(r) + "\n")

    total = time.time() - started
    print(f"\n\nwrote {out_path} -- {len(records)} exchanges "
          f"in {total / 60:.1f} min")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("events", help="events jsonl from event_generator.py")
    ap.add_argument("--out", default=None, help="output transcript path")
    ap.add_argument("--episodes", type=int, default=None,
                    help="only run the first N episodes")
    ap.add_argument("--verbose", action="store_true",
                    help="print each exchange as it happens")
    ap.add_argument("--seed", type=int, default=None,
                    help="sampling seed, so seeded runs differ in "
                         "generation as well as in events")
    args = ap.parse_args()

    if args.seed is not None:
        import mlx.core as mx
        mx.random.seed(args.seed)

    out = args.out or args.events.replace("events_", "transcript_")
    if out == args.events:
        out = "transcript.jsonl"

    run(args.events, out, args.episodes, args.verbose)


if __name__ == "__main__":
    main()